import jsPDF from 'jspdf';
import { ChatMessage, AppState, Citation } from '../types';

/**
 * Generates and downloads a structured Text/Markdown dossier file.
 */
export function exportToText(messages: ChatMessage[], state: AppState) {
  const timestamp = new Date().toLocaleString();
  const filename = `AyushIP_Regulatory_Dossier_${new Date().toISOString().slice(0, 10)}.txt`;

  let text = `================================================================================\n`;
  text += `                     AYUSH-IP REGULATORY DOSSIER REPORT                         \n`;
  text += `================================================================================\n`;
  text += `Generated Date       : ${timestamp}\n`;
  text += `Jurisdiction         : ${state.jurisdiction}\n`;
  text += `Formulation Category : ${state.formulationCategory}\n`;
  text += `Language Alignment   : Automatic (Matches Input)\n`;
  text += `================================================================================\n\n`;

  // Extract all citations
  const allCitations: Citation[] = [];
  messages.forEach(m => {
    if (m.citations) {
      m.citations.forEach(c => {
        if (!allCitations.some(existing => existing.source === c.source)) {
          allCitations.push(c);
        }
      });
    }
  });

  if (allCitations.length > 0) {
    text += `--------------------------------------------------------------------------------\n`;
    text += `CITED AYURVEDIC REGULATORY DOCUMENTS & AUTHORITY SOURCES (${allCitations.length})\n`;
    text += `--------------------------------------------------------------------------------\n`;
    allCitations.forEach((cit, idx) => {
      text += `[${idx + 1}] ${cit.source}\n`;
      if (cit.docCategory) text += `    Category    : ${cit.docCategory}\n`;
      if (cit.description) text += `    Mandate/Rule: ${cit.description}\n`;
      if (cit.url) text += `    Reference   : ${cit.url}\n`;
      text += `\n`;
    });
    text += `================================================================================\n\n`;
  }

  text += `--------------------------------------------------------------------------------\n`;
  text += `CONVERSATION TRANSCRIPT & REGULATORY ANALYSIS\n`;
  text += `--------------------------------------------------------------------------------\n\n`;

  messages.forEach((msg, idx) => {
    const roleLabel = msg.role === 'user' ? 'USER QUERY' : 'AYUSH-IP ASSISTANT';
    text += `--- [Message ${idx + 1}] ${roleLabel} ---\n\n`;
    text += `${msg.content}\n\n`;

    if (msg.role === 'assistant') {
      if (msg.confidence) {
        text += `Confidence Level: ${msg.confidence}\n`;
      }
      if (msg.needsHumanEscalation) {
        text += `[!] Human Facilitator Escalation Recommended\n`;
      }
      if (msg.citations && msg.citations.length > 0) {
        text += `Citations Referenced:\n`;
        msg.citations.forEach(c => {
          text += `  * ${c.source}${c.description ? ` - ${c.description}` : ''}\n`;
        });
      }
      text += `\n`;
    }
    text += `--------------------------------------------------------------------------------\n\n`;
  });

  text += `================================================================================\n`;
  text += `DISCLAIMER:\n`;
  text += `This dossier is generated by AyushIP for informational and educational purposes only.\n`;
  text += `It provides legal information grounded in regulatory frameworks, not formal legal advice.\n`;
  text += `Consult a certified Patent Agent or IP Attorney for legal representation.\n`;
  text += `================================================================================\n`;

  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(link.href);
}

/**
 * Generates and downloads a rich, multi-page PDF dossier using jsPDF.
 */
export function exportToPDF(messages: ChatMessage[], state: AppState) {
  const doc = new jsPDF({
    unit: 'pt',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const checkPageBreak = (neededHeight: number) => {
    if (y + neededHeight > pageHeight - margin - 30) {
      doc.addPage();
      y = margin;
      drawHeaderFooter();
    }
  };

  const drawHeaderFooter = () => {
    // Top bar decoration
    doc.setFillColor(79, 70, 229); // indigo-600
    doc.rect(margin, y - 10, contentWidth, 3, 'F');
  };

  // Title section
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(30, 41, 59); // slate-800
  doc.text('AyushIP - Regulatory & IP Dossier', margin, y + 15);
  y += 30;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text(`Generated: ${new Date().toLocaleString()}`, margin, y);
  y += 15;

  // Metadata Card Box
  doc.setFillColor(248, 250, 252); // slate-50
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.roundedRect(margin, y, contentWidth, 50, 6, 6, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text(`JURISDICTION:`, margin + 15, y + 20);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(79, 70, 229);
  doc.text(`${state.jurisdiction}`, margin + 95, y + 20);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(71, 85, 105);
  doc.text(`FORMULATION CATEGORY:`, margin + 200, y + 20);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(79, 70, 229);
  doc.text(`${state.formulationCategory}`, margin + 335, y + 20);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(71, 85, 105);
  doc.text(`LANGUAGE:`, margin + 15, y + 38);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(15, 23, 42);
  doc.text(`Auto-Aligned`, margin + 80, y + 38);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(71, 85, 105);
  doc.text(`MESSAGES RECORDED:`, margin + 200, y + 38);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(15, 23, 42);
  doc.text(`${messages.length}`, margin + 325, y + 38);

  y += 65;

  // Citations Overview Block
  const allCitations: Citation[] = [];
  messages.forEach(m => {
    if (m.citations) {
      m.citations.forEach(c => {
        if (!allCitations.some(existing => existing.source === c.source)) {
          allCitations.push(c);
        }
      });
    }
  });

  if (allCitations.length > 0) {
    checkPageBreak(80);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59);
    doc.text(`Cited Regulatory & Legal Authorities (${allCitations.length})`, margin, y);
    y += 15;

    allCitations.forEach((cit, idx) => {
      checkPageBreak(40);
      doc.setFillColor(241, 245, 249); // slate-100
      doc.roundedRect(margin, y, contentWidth, 32, 4, 4, 'F');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(15, 23, 42);
      const titleText = `${idx + 1}. ${cit.source}${cit.docCategory ? ` [${cit.docCategory}]` : ''}`;
      doc.text(titleText, margin + 10, y + 14);

      if (cit.description) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(71, 85, 105);
        const descText = doc.splitTextToSize(cit.description, contentWidth - 20);
        doc.text(descText[0] || '', margin + 10, y + 26);
      }
      y += 38;
    });

    y += 10;
  }

  // Conversation Section
  checkPageBreak(40);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(30, 41, 59);
  doc.text('Conversation & Insight Transcript', margin, y);
  y += 20;

  messages.forEach((msg) => {
    const isUser = msg.role === 'user';
    const roleTitle = isUser ? 'USER QUERY' : 'AYUSH-IP ASSISTANT RESPONSE';
    
    // Clean markdown text for PDF display
    const cleanContent = msg.content
      .replace(/#{1,6}\s?/g, '')
      .replace(/\*\*(.*?)\*\*/g, '$1')
      .replace(/\*(.*?)\*/g, '$1')
      .replace(/`{1,3}(.*?)`{1,3}/g, '$1');

    const splitText = doc.splitTextToSize(cleanContent, contentWidth - 24);
    const boxHeight = splitText.length * 11 + 32;

    checkPageBreak(boxHeight + 10);

    if (isUser) {
      doc.setFillColor(238, 242, 255); // indigo-50
      doc.setDrawColor(199, 210, 254); // indigo-200
    } else {
      doc.setFillColor(255, 255, 255);
      doc.setDrawColor(226, 232, 240); // slate-200
    }

    doc.roundedRect(margin, y, contentWidth, boxHeight, 6, 6, 'FD');

    // Header inside message box
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(isUser ? 79 : 15, isUser ? 70 : 23, isUser ? 229 : 42);
    doc.text(roleTitle, margin + 12, y + 16);

    // Message Body
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(51, 65, 85);

    let textY = y + 28;
    splitText.forEach((line: string) => {
      if (textY < y + boxHeight - 8) {
        doc.text(line, margin + 12, textY);
        textY += 11;
      }
    });

    y += boxHeight + 12;

    // Citations list if present
    if (msg.citations && msg.citations.length > 0) {
      checkPageBreak(msg.citations.length * 15 + 20);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(71, 85, 105);
      doc.text('Referenced Regulatory Documents:', margin + 10, y);
      y += 12;

      msg.citations.forEach(cit => {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(79, 70, 229);
        doc.text(`• ${cit.source}${cit.description ? `: ${cit.description}` : ''}`, margin + 20, y);
        y += 12;
      });
      y += 6;
    }
  });

  // Disclaimer at the bottom
  checkPageBreak(50);
  y += 10;
  doc.setDrawColor(226, 232, 240);
  doc.line(margin, y, margin + contentWidth, y);
  y += 15;

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(7.5);
  doc.setTextColor(148, 163, 184);
  const disclaimer = "Disclaimer: This report is generated by AyushIP AI for informational and research purposes. It does not constitute formal legal counsel. For statutory IP filings or litigation, please consult a certified Patent Attorney or Ayush Legal Practitioner.";
  const splitDisclaimer = doc.splitTextToSize(disclaimer, contentWidth);
  splitDisclaimer.forEach((line: string) => {
    doc.text(line, margin, y);
    y += 10;
  });

  doc.save(`AyushIP_Regulatory_Dossier_${new Date().toISOString().slice(0, 10)}.pdf`);
}
